### ISSUE TITLE
建议在Markdown链接语法的前后添加空格

### ISSUE THREAD

**Issue by ehehela** [sethyuan/logseq-plugin-charspacing#17]
例如，把原来这样的显示效果（是显示效果，文档内容不加空格）：

> 这是一个链接[github](https://github.com)地址

改成

> 这是一个链接 [github](https://github.com) 地址

**Comment by sethyuan** [comment]
现在应该就是这种效果，你的原文是什么样的？

**Comment by ehehela** [comment]
不好意思我说错了，我希望是无论中英文，均能在`[`之前和`)`之后加一个空格
比如，现在的显示效果为

> 这是一个链接[仓库](https://github.com)地址

我希望它能这样

> 这是一个链接 [仓库](https://github.com) 地址

**Comment by sethyuan** [comment]
这可能已经超出这个插件的功能范围了。不过你可以试试在你的custom.css文件中自定义链接的样式，加上margin。

**Comment by ehehela** [comment]
谢谢，我琢磨琢磨

**Comment by ehehela** [comment]
成功
```css
.external-link::before, /* 给链接前后增加空格 */
.external-link::after,
.block-ref:not(:has(.block-content.inline))::before,  /* 给块引用（排除块引用后代含有.block-content.inline的）前添加空格， */
.block-ref::after {     /* 给块引用后添加空格 */
      display: inline;
      content: " ";
}
```
