### ISSUE TITLE
关于latex和中文之间添加空格的建议

### ISSUE THREAD

**Issue by jayus71** [sethyuan/logseq-plugin-charspacing#6]
首先插件已经实现的功能确实使文档变美观了很多，但是有一点建议，**latex公式和中文**之间可否也加上空呢，现在也是紧贴着的，有点丑有一说一
![20220416151406](https://user-images.githubusercontent.com/62584977/163665725-ab8785a8-6048-465b-a2a0-13acd71b06bb.png)
。

**Comment by sethyuan** [comment]
这个对于本插件来说可能有点超纲了，不过你可以尝试在你自己的 `custom.css` 中添加下面这段代码，再根据需要进行调整：

```css
.latex-inline {
  margin: 0 0.2em;
}
```

`0.2em` 是你想要的间距大小。
